services:
  backend:
    build:
      context: ./
      target: node-20
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    command: >
      sh -c "npm install && npm run start"
    volumes:
      node_vol:
