version: "3.8"

services:
  backend:
    image: aayush112/foodx-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - foodx-images:/app/uploads
      - foodx-logs:/app/logs


volumes:
  foodx-images:
  foodx-logs:
