services:
  backend:
    image: aayush112/foodx-backend
    build:
      context: ./
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: >
      sh -c "npm install && npm run start"
    volumes:
      - .:/app
      - /app/node_modules
      - foodx-images:/app/uploads

volumes:
  foodx-images:
